### ISSUE TITLE
Regression: on demo site, after login, the main page doesn't load

### ISSUE THREAD

**Issue by alurm** [OktopUSP/oktopus#200]
(Login seems to be working fine, I entered `demo@gmail.com` and `demo` as credentials.)

Screenshots are from Firefox Nightly 122 and Chromium 112.

![image](https://github.com/OktopUSP/oktopus/assets/108410815/a021fecb-0e16-49a4-9091-aeb82fe1368e)

![image](https://github.com/OktopUSP/oktopus/assets/108410815/3cefebf4-be34-4b89-ba0e-5717bef1e7fa)

Some error logs.

```
TypeError: s.substring is not a function
    at OverviewTasksProgress (index-80ad44adf5badcc9.js:1:511)
    at Xh (framework-0c7baedefba6b077.js:9:60990)
    at x (framework-0c7baedefba6b077.js:9:119445)
    at Vk (framework-0c7baedefba6b077.js:9:99130)
    at framework-0c7baedefba6b077.js:9:98997
    at Jk (framework-0c7baedefba6b077.js:9:99004)
    at Ok (framework-0c7baedefba6b077.js:9:95760)
    at Hk (framework-0c7baedefba6b077.js:9:94316)
    at J (framework-0c7baedefba6b077.js:33:1364)
    at MessagePort.R (framework-0c7baedefba6b077.js:33:1894)

TypeError: s.substring is not a function
    at OverviewTasksProgress (index-80ad44adf5badcc9.js:1:511)
    at Xh (framework-0c7baedefba6b077.js:9:60990)
    at x (framework-0c7baedefba6b077.js:9:119445)
    at Vk (framework-0c7baedefba6b077.js:9:99130)
    at framework-0c7baedefba6b077.js:9:98997
    at Jk (framework-0c7baedefba6b077.js:9:99004)
    at Ok (framework-0c7baedefba6b077.js:9:95760)
    at Hk (framework-0c7baedefba6b077.js:9:94316)
    at J (framework-0c7baedefba6b077.js:33:1364)
    at MessagePort.R (framework-0c7baedefba6b077.js:33:1894)
```

**Comment by leandrofars** [comment]
Hi @alurm,
I've launched a new website: [https://demo.oktopus.app.br](https://demo.oktopus.app.br/), can you see if it solved the problem? If so, mark this comment as answer and close the issue. 
Thanks in advance.

**Comment by alurm** [comment]
Hi @leandrofars, I can't check that, since it's not logging in for me when using the demo credentials.

![image](https://github.com/OktopUSP/oktopus/assets/108410815/f85f0fdd-dbcc-437e-8334-c89fe5ef1075)

**Comment by leandrofars** [comment]
I'm sorry @alurm , forgot to register demo user, now it's available.
